app/internal_packages/edison-beijing-chat/components/chat/messages/OnlineStatus.jsx
app/internal_packages/edison-beijing-chat/store/ConversationStore.es6

this bug is when add a new message, show outline bar, because current user is null when add a new message

add new message dont show outline bar

---

app/internal_packages/composer-templates/lib/preferences-templates.jsx
app/internal_packages/preferences/lib/components/preferences-identity.jsx
app/internal_packages_disabled/activity/lib/dashboard/root.jsx
app/menus/darwin.json
app/src/browser/application.es6
app/src/browser/autoupdate-impl-base.es6
app/src/default-client-helper.es6
app/src/flux/models/query.es6

URL Change and Cross DB Linking issue

---

app/internal_packages/message-list/lib/email-frame.jsx
app/src/native-notifications.es6

DC-1220: No auto wrapped text in special mail
before close notification, need ensure it's not destroyed

Edison beijing chat zhansheng

---

app/internal_packages/category-picker/lib/create-new-folder-popover.jsx
app/internal_packages/category-picker/lib/create-new-label-popover.jsx
app/internal_packages/category-picker/lib/label-picker-popover.jsx
app/internal_packages/category-picker/lib/move-picker-popover.jsx
app/internal_packages/category-picker/lib/toolbar-category-picker.jsx
app/internal_packages/message-list/lib/message-list.jsx
app/internal_packages/message-list/styles/message-list.less
app/internal_packages/thread-list/lib/injects-toolbar-buttons.jsx
app/src/components/mail-label-set.jsx
app/static/components/extra.less

Bunch of label/move folder related UI flow change

DC-1270 Message List View Label issues

---

app/internal_packages/composer/lib/action-bar-plugins.jsx
app/src/components/empty-list-state.jsx

Fixed
React State setting after component unmounted 
React Props checking for EmptyListState

Minor Bug fixes

---

app/src/flux/models/message.es6
app/src/flux/stores/draft-factory.es6

DC-1681 The draft dosen't upload to server on account change

DC-1681 The draft dosen't upload to server on account change

---

app/src/components/multiselect-split-interaction-handler.es6

[Feedback]I am able to move through the messages—UNTIL I select a message with "X."

DC-1719 Backport

---

app/internal_packages/account-sidebar/lib/sidebar-item.es6
app/internal_packages/account-sidebar/lib/sidebar-section.es6
app/internal_packages/thread-list/lib/thread-list-columns.jsx
app/src/flux/mailsync-bridge.es6
app/src/flux/stores/category-store.es6
app/src/mailbox-perspective.es6

Draft icon in thread list, and folder tree issue fix

DC-1717, DC-1730, DC-1693

---

app/src/components/composer-editor/base-block-plugins.jsx
app/src/components/composer-editor/inline-attachment-plugins.jsx

[Insert Photo] Can't input texts when clicking on inline images during composing.

DC-1725 Can't input text after deleting inline image

---

app/internal_packages/thread-list/lib/thread-list-empty-folder-bar.jsx
app/src/components/multiselect-toolbar.jsx
app/src/services/search/search-query-backend-local.es6

DC-1766 Add remoteSearch field to ThreadSearch 
DC-1753 [Actions] Delete all is missing in Spam folder

DC-1753, DC-1766

---

app/internal_packages/thread-search/lib/search-query-subscription.es6
app/internal_packages/thread-search/lib/search-store.es6
app/src/flux/models/query.es6
app/src/flux/tasks/imap-search-task.es6

* gmail default search folder is all mail, other is inbox
* search every input change
* when receive native task is success close search loading

gmail default search is all mail,other is inbox

---

app/internal_packages/message-list/lib/message-list.jsx
app/internal_packages/message-list/lib/message-timestamp.jsx
app/internal_packages/pdf/static/print-styles.css
app/internal_packages/print/static/print-styles.css
app/src/flux/models/message.es6

ticket 173726: want select part of message subject
DC-1847:[Feedback]Need date and time in email header for printed copy
"unsubscription" button dispear

want select part of message subject

---

app/internal_packages/message-list/lib/message-controls.jsx
app/internal_packages/message-list/lib/message-list.jsx

change message box buttons to display "ok" only

DC-1851 Disable reply/forward function when in trash/spam view

---

app/internal_packages/account-sidebar/lib/sidebar-actions.es6
app/internal_packages/account-sidebar/lib/sidebar-item.es6
app/internal_packages/account-sidebar/lib/sidebar-section.es6
app/internal_packages/account-sidebar/lib/sidebar-store.es6
app/src/components/disclosure-triangle.jsx
app/src/components/outline-view-item.jsx
app/src/components/outline-view.jsx
app/src/flux/actions.es6
app/src/flux/models/utils.es6
app/src/flux/stores/category-store.es6
app/static/components/outline-view.less

DC-1867 Add more when there are lots of folders
DC-1932 Folder list not sorted alphabetically

DC-1867 and DC-1932

---

app/src/flux/models/unread-query-subscription.es6

DC-1945 [Undo] Undo function works incorrectly

---

app/static/components/outline-view.less

Reverts agent8/Mailspring#535
Hilary agrees we should use 14px

Revert "Make folder list more compact"

---

app/internal_packages/message-list/lib/message-item.jsx
app/internal_packages/message-list/styles/message-list.less
app/internal_packages/preferences/lib/preferences-template-fill.jsx
app/internal_packages/thread-list/lib/thread-toolbar-buttons.jsx
app/src/components/list-tabular-item.jsx
app/static/components/list-tabular.less

DC-1969 when click [More] button, nothing pop up
add [Default reply behavior] to preferences

DC-1969 when click [More] button, nothing pop up

---

app/internal_packages/message-list/lib/message-controls.jsx
app/src/flux/models/category.es6
app/src/flux/models/message.es6
app/src/flux/models/thread.es6
app/src/flux/stores/message-store.es6
app/src/flux/stores/recently-read-store.es6
app/src/flux/tasks/make-other-task.es6
app/src/flux/tasks/make-primary-task.es6
app/src/mailbox-perspective.es6

Focus Inbox related thread/message update fixes
This makes PR  #550 redundant

DC-1978, DC-1975

---

app/internal_packages/print/static/print.js
app/internal_packages/ui-dark/styles/override-email.less
app/static/email-frame.less

DC-2021 [Feedback] email can't print rarely
DC-2023 [Feedback] Plain text mail appears to show as monospaced font

DC-2021, DC-2023

---

app/internal_packages/message-list/lib/message-item.jsx
app/internal_packages/thread-list/lib/thread-list-data-source.es6
app/internal_packages/thread-list/lib/thread-toolbar-buttons.jsx
app/src/components/list-selection.es6
app/src/constant.es6
app/src/flux/models/category.es6
app/src/flux/models/unread-query-subscription.es6
app/src/flux/stores/message-store.es6
app/src/flux/stores/observable-list-data-source.es6
app/src/flux/stores/recently-read-store.es6
app/src/global/mailspring-observables.es6
app/src/mailbox-perspective.es6

In addition to DC-2015
This PR includes adding different source to ChangeUnreadTask

DC-2015 [Unread] Cannot mark mail in unread folder at the first time

---

app/internal_packages/thread-list/lib/thread-toolbar-buttons.jsx
app/internal_packages/undo-redo/lib/undo-redo-toast.jsx
app/src/flux/tasks/expunge-messages-task.es6
app/src/flux/tasks/task-factory.es6

Expunge Messages/Threads improvements

---

app/src/components/composer-editor/base-mark-plugins.jsx
app/src/components/composer-editor/toolbar-component-factories.jsx
app/src/config-schema.es6

Summary of PR:
- Added `core.fontface` to `AppEnv.config` schema
- `DEFAULT_FONT_FACE` which the composer refers to when deciding the default font is now set as `core.fontface`

[Composer] Remember last font used

---

app/src/flux/stores/account-store.es6

remove based on June 28th 1917 hours meeting

Remove updateWakeWorkerTimer in UI

---

app/internal_packages/preferences/lib/preferences-template-fill.jsx
app/src/config-schema.es6
app/src/flux/stores/draft-store.es6

Summary of PR:
- Added `core.reading.openReplyInNewWindow` to AppEnv.config schema
- Modify logic to first check for preference option when deciding to open new window

[Preferences] Option for Opening Reply in New Window

---

app/src/app-env.es6
app/src/flux/stores/draft-store.es6

DC-2146 [Trash] Trash label is replaced when user create [Gmail]/Trash

---

app/src/flux/stores/draft-editing-session.es6

we moved  _bodyHTMLCache = inHTML to top, in case body replace failed, our data to DB would still be correct

DC-2225 replacing body failed for draft

---

app/internal_packages/composer/lib/composer-view.jsx
app/src/flux/actions.es6
app/src/flux/stores/attachment-store.es6
app/src/flux/stores/draft-store.es6

Fix DC-2206 and refactored inline attachment removal

DC-2206 [UI] Shouldn't show attachment when reply a mail then delete original mail

---

app/internal_packages/preferences/lib/components/preferences-appearance-components.jsx
app/internal_packages/preferences/styles/preferences-appearance.less
app/static/workspace.less

UI fix for reading pane bottom
can't drag window

UI fix for reading pane bottom

---

app/internal_packages/onboarding/lib/decorators/create-page-for-form.jsx
app/src/components/evented-iframe.jsx

if user login Office365 account through Exchange entry, notify the user
DC-2420 [Feedback] Command +/- is very buggy and is not very consistent

if user login Office365 account through Exchange entry, notify the user and DC-2420

---

app/internal_packages/category-picker/styles/category-picker.less
app/internal_packages/preferences/lib/components/preferences-account-details.jsx
app/internal_packages/preferences/lib/components/preferences-keymaps.jsx
app/internal_packages/preferences/styles/preferences-category.less
app/internal_packages/preferences/styles/preferences.less

Revert "electron 9 UI issue fix: dropdown"

---

app/package.json
app/src/browser/main.js
app/yarn.lock
package.json

Revert "upgrade Electron from 6.1.12 to 9.3.2"

---

app/internal_packages/preferences/styles/preferences.less
app/src/components/dropdown-menu.jsx

Revert "electron 9 UI issue fix"

---

app/internal_packages/composer-signature/lib/signature-composer-extension.es6
app/internal_packages/composer-signature/lib/signature-utils.es6

DC-2431 Adding account default signature will change draft pristine to false

DC-2431 Adding account default signature will change draft pristine

---

app/internal_packages/message-list/lib/body-remove-trackers.es6

DC-2436 [Feedback] remove-tracker blocked wrong image

---

app/internal_packages/preferences/lib/components/preferences-account-details.jsx
app/internal_packages/preferences/lib/components/preferences-general-components.jsx
app/internal_packages/preferences/lib/preferences-template-fill.jsx
app/src/browser/application.es6

DC-2478 MailSync Settings for Enable Focused Inbox does not update after account added

DC-2478 MailSync Settings for Enable Focused Inbox does not update

---

app/internal_packages/category-picker/lib/label-picker-popover.jsx
app/src/components/menu.jsx
app/src/flux/stores/draft-factory.es6

DC-2623 [Feedback] keyboard operation is not convenience
DC-2632 [Feedback] reply there are 2 spaces, but start a new message there is one space

Db refactor quanzs

---

app/internal_packages/message-list/lib/message-item.jsx
app/internal_packages/thread-list/styles/thread-list.less

UI issue: when click reply, the avatar in thread list shakes
When click the contacts in message header, the message-item should no… …

minor improvements

---

app/src/components/composer-editor/spellcheck-plugins.jsx

Japanese input issue: when using space key to choose suggestions, should not execute spellcheck

Japanese input issue

---

app/internal_packages/thread-list/lib/main.es6
app/internal_packages/thread-search/lib/main.jsx
app/internal_packages/thread-search/lib/title-search-bar.jsx
app/internal_packages/thread-search/styles/thread-search-bar.less
app/package.json
app/src/components/list-detail-container.jsx
app/src/components/multiselect-toolbar.jsx
app/static/components/list-tabular.less
app/static/workspace.less

1. can drag the multi selection bar anywhere
2. move the title and search bar from [Toolbar] into [Center] component

DC-2729 Selection/cursor moves actions:

---

app/internal_packages/jira-plugin/lib/jira-detail.jsx
app/internal_packages/message-list/lib/message-list.jsx
app/internal_packages/preferences/lib/components/preferences-account-list.jsx
app/internal_packages/thread-list/lib/thread-toolbar-buttons.jsx
app/internal_packages/thread-search/lib/tokenizing-contenteditable.es6
app/src/app-env.es6
app/src/components/composer-editor/composer-editor.jsx
app/src/components/evented-iframe.jsx
app/src/components/multiselect-toolbar.jsx
app/src/components/tokenizing-text-field.jsx
app/src/flux/actions.es6
app/src/flux/stores/context-menu-store.es6

should perform a full test before merging into production

DC-2708 Right click menu should not show at the same time

---

app/internal_packages/preferences/lib/preferences-template-fill.jsx
app/src/components/composer-editor/base-block-plugins.jsx
app/src/config-schema.es6

DC-2755 [Feedback] Automatically Show Message History in Reply Window

---

app/internal_packages/composer/styles/composer.less
app/internal_packages/jira-plugin/lib/jira-comments.jsx
app/internal_packages/jira-plugin/lib/jira-detail.jsx

DC-2837 [JIRA] Should not show delete action for the comments of other user
DC-2836 [UI] The buttons should not be out of composer boundary
DC-2841 [JIRA] Fail to open mp4 files from attachment

DC-2836, DC-2837, DC-2841

---

app/internal_packages/message-list/lib/message-item.jsx
app/internal_packages/pdf/static/print-styles.css
app/internal_packages/print/static/print-styles.css
app/src/components/attachment-items.jsx
app/src/rest/edison-account.es6
app/src/rest/preferences.es6
app/static/components/list-tabular.less

DC-2895 [Feedback] thread list checkmark icon shows as 1px clipped
DC-2892 [Print] It does not show all info in print window
DC-2908 The pdf attachment cannot show in print view.

DC-2895, DC-2892, DC-2908

---

app/internal_packages/account-color/lib/account-color.jsx
app/internal_packages/account-color/lib/main.es6
app/internal_packages/account-color/package.json
app/internal_packages/draft-list/lib/draft-list-columns.jsx
app/internal_packages/draft-list/lib/draft-list.jsx
app/internal_packages/outbox/lib/outbox-list-columns.jsx
app/internal_packages/outbox/lib/outbox-list.jsx
app/internal_packages/preferences/styles/preferences.less
app/internal_packages/sift-list/lib/sift-list-columns.jsx
app/internal_packages/sift-list/lib/sift-list.jsx

DC-2968 and DC-2978

---

app/internal_packages/account-sidebar/lib/sidebar-item.es6
app/internal_packages/composer/lib/composer-header.jsx
app/internal_packages/thread-list/lib/thread-list-data-source.es6
app/internal_packages/thread-list/lib/thread-list-quick-actions.jsx
app/src/mailbox-perspective.es6

DC-2986 [Recently Seen] Some issues in recently seen …
DC-2981 [JIRA] It always show archive action on email in JIRA assistant
DC-2995 [Composer] Spell checking does not work correctly

DC-2986 DC-2981 DC-2995
